name: Build (xgo)

on:
  push:
  pull_request:

jobs:
  build:
    name: xgo
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          path: "./src/github.com/elsaland/elsa"

      - name: Setup node (for benchmarks)
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup go
        uses: actions/setup-go@v2
      
      - name: Setup xgo
        run: go get src.techknowlogick.com/xgo
      
      - name: Install go-bindata
        run: go get github.com/go-bindata/go-bindata

      - name: Run bootstrap
        working-directory: ./src/github.com/elsaland/elsa
        run: |
          go run ./bootstrap/
          go mod vendor
          go build .
      
      - name: Build
        working-directory: ./src/github.com/elsaland/elsa
        run: go run src.techknowlogick.com/xgo --targets=linux/arm github.com/elsaland/elsa
